name: Testing
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: cd directory
        run: cd build

      - name: install and test
        run: |
          .\install.bat
          .\install\bin\hello_world.exe
