name: Testing
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: ls
        run: ls
        
      - name: install and test
        run: |
          cd build
          .\install.bat
          .\install\bin\hello_world.exe
